### ISSUE TITLE
crash in NewGideWindow

### ISSUE THREAD

**Issue by rcoreilly** [goki/gide#304]
```
crash_2023-12-24_21-09-51
oreilly@MacBook-Pro:~/Library/goki/ > more crash-logs/gide/crash_2023-12-24_21-09-51 
panic: interface conversion: ki.Ki is nil, not *gidev.GideView

----- START OF STACK TRACE: -----
goroutine 3602219 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/debug/stack.go:24 +0x64
goki.dev/goosi.HandleRecoverBase({0x1033c92e0, 0x1402a71ce10})
        /Users/oreilly/go/src/goki.dev/goosi/recover.go:50 +0x38
goki.dev/goosi.glob..func1({0x1033c92e0, 0x1402a71ce10})
        /Users/oreilly/go/src/goki.dev/goosi/recover.go:33 +0x24
goki.dev/gi/v2/gi.(*RenderWin).EventLoop.func1()
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/renderwin.go:558 +0x34
panic({0x1033c92e0?, 0x1402a71ce10?})
        /opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/panic.go:914 +0x218
goki.dev/gide/v2/gidev.GideInScene(...)
        /Users/oreilly/go/src/goki.dev/gide/v2/gidev/gideview.go:550
goki.dev/gide/v2/gidev.NewGideWindow({0x140356de210, 0x23}, {0x140141fb486?, 0x100d9aa90?}, {0x140141fb473, 0x18}, 0x0)
        /Users/oreilly/go/src/goki.dev/gide/v2/gidev/gideview.go:560 +0x41c
goki.dev/gide/v2/gidev.OpenGideProj({0x140356de210, 0x23})
        /Users/oreilly/go/src/goki.dev/gide/v2/gidev/gideview.go:546 +0xb4
goki.dev/gide/v2/gidev.(*GideView).OpenProj(0x140356de090?, {0x140356de210?, 0x0?})
        /Users/oreilly/go/src/goki.dev/gide/v2/gidev/gideview.go:281 +0x308
goki.dev/gide/v2/gidev.(*GideView).OpenPath(0x1404389f400, {0x140356de090, 0x24})
        /Users/oreilly/go/src/goki.dev/gide/v2/gidev/gideview.go:248 +0x34c
reflect.Value.call({0x1033683c0?, 0x1405e3824a0?, 0x16a9d20c0?}, {0x101aa6744, 0x4}, {0x1404be56918, 0x1, 0x0?})
        /opt/homebrew/Cellar/go/1.21.4/libexec/src/reflect/value.go:596 +0x994
reflect.Value.Call({0x1033683c0?, 0x1405e3824a0?, 0x14004f513c8?}, {0x1404be56918?, 0x1402a391180?, 0x1033460a0?})
        /opt/homebrew/Cellar/go/1.21.4/libexec/src/reflect/value.go:380 +0x94
goki.dev/gi/v2/giv.(*FuncButton).CallFuncShowReturns(0x1402251ed00)
        /Users/oreilly/go/src/goki.dev/gi/v2/giv/funcbutton.go:262 +0x148
goki.dev/gi/v2/giv.(*FuncButton).CallFunc.func1()
        /Users/oreilly/go/src/goki.dev/gi/v2/giv/funcbutton.go:293 +0x20
goki.dev/gi/v2/giv.OpenValueDialog.func2.1({0x1403090d000?, 0x103561360?})
        /Users/oreilly/go/src/goki.dev/gi/v2/giv/value.go:937 +0x84
goki.dev/gi/v2/giv.OpenValueDialog.func2.(*WidgetBase).OnClick.(*WidgetBase).On.func2({0x103569d28, 0x1402a390fc0})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/events.go:35 +0x7c
goki.dev/goosi/events.(*Listeners).Call(0x1403090d700, {0x103569d28, 0x1402a390fc0})
        /Users/oreilly/go/src/goki.dev/goosi/events/listeners.go:58 +0xa4
goki.dev/gi/v2/gi.(*WidgetBase).HandleEvent(0x1403090d000, {0x103569d28, 0x1402a390fc0})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/events.go:198 +0x1a0
goki.dev/gi/v2/gi.(*WidgetBase).Send(0x1403090d000, 0x5, {0x14004f51668, 0x1, 0x14004f51678?})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/events.go:134 +0x180
goki.dev/gi/v2/gi.(*Scene).AddOk.func2({0x103569f88, 0x1402a390ee0})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/dialogs.go:125 +0xa8
goki.dev/gi/v2/gi.(*Scene).AddOk.(*WidgetBase).OnKeyChord.(*WidgetBase).On.func4({0x103569f88, 0x1402a390ee0})
        /Users/oreilly/go/src/goki.dev/gi/v2/gi/events.go:35 +0x7c
goki.dev/goosi/events.(*Listeners).Call(0x14058f48700, {0x103569f88, 0x1402a390ee0})
        /Users/oreilly/go/src/goki.dev/goosi/events/listeners.go:58 +0xa4
goki.dev/gi/v2/gi.(*WidgetBase).HandleEvent(0x14058f48000, {0x103569f88, 0x1402a390ee0})
```

**Comment by rcoreilly** [comment]
added a guard for this case
