### ISSUE TITLE
edit nil point

### ISSUE THREAD

**Issue by ddkwork** [goki/gide#307]
At the moment I'm not ready to participate in your development in any easy way, so I'm reporting bugs and fixes in this way for the time being. Bug recurrence, pull the latest commit to run gide, click on the middle of the framework area, panic occurs, the code editor is not instantiated, then you should judge whether buf is nil

![{A3D52C46-A1B3-437a-9CEB-39C9384C341E}](https://github.com/goki/gide/assets/19886504/e769ac90-71ea-4117-a608-3f9f7e7d3fb2)

**Comment by ddkwork** [comment]
```go
GOROOT=C:\Users\Admin\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.21.5.windows-amd64 #gosetup
GOPATH=C:\Users\Admin\go #gosetup
C:\Users\Admin\go\pkg\mod\golang.org\toolchain@v0.0.1-go1.21.5.windows-amd64\bin\go.exe build -o C:\Users\Admin\AppData\Local\JetBrains\GoLand2023.3\tmp\GoLand\___1go_build_goki_dev_gide_v2_cmd_gide.exe goki.dev/gide/v2/cmd/gide #gosetup
C:\Users\Admin\AppData\Local\JetBrains\GoLand2023.3\tmp\GoLand\___1go_build_goki_dev_gide_v2_cmd_gide.exe
2024/01/09 01:36:14 ERROR open C:\Users\Admin\AppData\Roaming\gide\splits_prefs.json: The system cannot find the file specified.
2024/01/09 01:36:14 ERROR open C:\Users\Admin\AppData\Roaming\gide\registers_prefs.toml: The system cannot find the file specified.
2024/01/09 01:36:14 ERROR girl/paint.FontLib: error accessing path path=. err=stat .: os: DirFS with empty root
2024/01/09 01:36:14 ERROR girl/paint.FontLib: error walking path path= err=stat .: os: DirFS with empty root
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0xa88 pc=0x7ff651b7e7ac]

goroutine 50 [running]:
goki.dev/goosi.HandleRecoverPanic({0x7ff652125540, 0x7ff651fc3920})
        D:/workspace/workspace/ux/goosi/recover.go:85 +0x9a
goki.dev/goosi.glob..func1({0x7ff652125540, 0x7ff651fc3920})
        D:/workspace/workspace/ux/goosi/recover.go:34 +0x2c
goki.dev/gi/v2/gi.(*RenderWin).EventLoop.func1()
        D:/workspace/workspace/ux/gi/gi/renderwin.go:567 +0x24
panic({0x7ff652125540?, 0x7ff651fc3920?})
        C:/Users/Admin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.5.windows-amd64/src/runtime/panic.go:914 +0x21f
goki.dev/gix/texteditor.(*Buf).NumLines(0x7ff650f42165?)
        D:/workspace/workspace/ux/gix/texteditor/buf.go:341 +0x2c
goki.dev/gix/texteditor.(*Buf).IsValidLine(...)
        D:/workspace/workspace/ux/gix/texteditor/buf.go:351
goki.dev/gide/v2/gide.(*TextEditor).HandleEvents.func2({0x7ff653ad3af0, 0xc00178e7e0})
        D:/workspace/workspace/ux/gide/gide/texteditor.go:54 +0x93
goki.dev/gide/v2/gide.(*TextEditor).HandleEvents.(*WidgetBase).OnDoubleClick.(*WidgetBase).On.func6({0x7ff653ad3af0, 0xc00178e7e0})
        D:/workspace/workspace/ux/gi/gi/events.go:39 +0x6f
goki.dev/goosi/events.(*Listeners).Call(0xc0003e2320, {0x7ff653ad3af0, 0xc00178e7e0})
        D:/workspace/workspace/ux/goosi/events/listeners.go:58 +0xa2
goki.dev/gi/v2/gi.(*WidgetBase).HandleEvent(0xc0003e1c00, {0x7ff653ad3af0?, 0xc00178e7e0})
        D:/workspace/workspace/ux/gi/gi/events.go:202 +0x1af
goki.dev/gi/v2/gi.(*EventMgr).HandlePosEvent(0xc0003e1928, {0x7ff653ad3af0, 0xc00178e7e0})
        D:/workspace/workspace/ux/gi/gi/eventmgr.go:275 +0x510
goki.dev/gi/v2/gi.(*EventMgr).HandleEvent(0xc0000e4000?, {0x7ff653ad3af0, 0xc00178e7e0})
        D:/workspace/workspace/ux/gi/gi/eventmgr.go:154 +0x58
goki.dev/gi/v2/gi.(*Stage).MainHandleEvent(0xc0000e1680, {0x7ff653ad3af0?, 0xc00178e7e0})
        D:/workspace/workspace/ux/gi/gi/mainstage.go:303 +0x165
goki.dev/gi/v2/gi.(*StageMgr).MainHandleEvent(0xc000642f18, {0x7ff653ad3af0, 0xc00178e7e0})
        D:/workspace/workspace/ux/gi/gi/mainstage.go:311 +0x6e
goki.dev/gi/v2/gi.(*RenderWin).HandleEvent(0xc000642ee0, {0x7ff653ad3af0, 0xc00178e7e0})
        D:/workspace/workspace/ux/gi/gi/renderwin.go:613 +0x114
goki.dev/gi/v2/gi.(*RenderWin).EventLoop(0xc000642ee0)
        D:/workspace/workspace/ux/gi/gi/renderwin.go:579 +0x5e
created by goki.dev/gi/v2/gi.(*RenderWin).GoStartEventLoop in goroutine 1
        D:/workspace/workspace/ux/gi/gi/renderwin.go:535 +0xa5

Process finished with the exit code 2

```

**Comment by ddkwork** [comment]
```go
// SelectWord selects the word (whitespace, punctuation delimited) that the cursor is on
// returns true if word selected
func (ed *Editor) SelectWord() bool {
	if ed.Buf == nil {
		return false
	}
	txt := ed.Buf.Line(ed.CursorPos.Ln)
	sz := len(txt)
	if sz == 0 {
		return false
	}
	reg := ed.WordAt()
	ed.SelectReg = reg
	ed.SelectStart = ed.SelectReg.Start
	return true
}
```

**Comment by ddkwork** [comment]
```go
// TextEditorEvents sets connections between mouse and key events and actions
func (ed *TextEditor) HandleEvents() {
	ed.On(events.Focus, func(e events.Event) {
		ed.Gide.SetActiveTextEditor(ed)
	})
	ed.OnDoubleClick(func(e events.Event) {
		pt := ed.PointToRelPos(e.LocalPos())
		tpos := ed.PixelToCursor(pt)
		if ed.Buf != nil && pt.X >= 0 && ed.Buf.IsValidLine(tpos.Ln) {
			if pt.X < int(ed.LineNoOff) {
				e.SetHandled()
				ed.LineNoDoubleClick(tpos)
				return
			}
			ed.HandleDebugDoubleClick(e, tpos)
		}
	})
	ed.On(events.LongHoverStart, func(e events.Event) {
		tt := ""
		vv := ed.DebugVarValueAtPos(e.LocalPos())
		if vv != "" {
			tt = vv
		}
		// todo: look for documentation on symbols here -- we don't actually have this
		// in pi so we need lsp to make this work
		if tt != "" {
			e.SetHandled()
			pos := e.LocalPos()
			pos.X += 20
			pos.Y += 20
			gi.NewTooltipText(ed, tt).SetPos(pos).Run()
		}
	})
}
```

**Comment by ddkwork** [comment]
Based on the principle of horizontal split layout that I Xi learned from you before, in Gide I propose to change the instantiation logic of the code editor control, so that you can't check that null pointers are everywhere if xxx is nil, which will affect readability and maintainability. At present, the code editor is a multi-page editing implemented by splitting the layout, i.e., one area per file, then each area is instantiated and a textbuf is forced to be instantiated, instead of letting the user display the instantiation of it. This eliminates the code that is full of nil checks, and the textbuf data structure is exported, so a textedit and a textbuf should correspond one-to-one, which also simplifies the embarrassment of the user having to write a long textbuf instantiation code, the textbuf pointer should be nested inside the textedit data structure, it should be the edit struct member. What do you think of this proposal?

**Comment by ddkwork** [comment]
https://github.com/goki/gi/discussions/745

**Comment by rcoreilly** [comment]
I'm not 100% sure about what you're saying but it is essential that you are able to have 2 (or more!) different views (editors) working on the same underlying text buffer.  I am often editing one part of a file while looking at another part of it in the other editor.  Therefore, we cannot make it one-to-one between buffer and editor.

**Comment by ddkwork** [comment]
> I'm not 100% sure about what you're saying but it is essential that you are able to have 2 (or more!) different views (editors) working on the same underlying text buffer.  I am often editing one part of a file while looking at another part of it in the other editor.  Therefore, we cannot make it one-to-one between buffer and editor.
> 

bug report

**Comment by ddkwork** [comment]
Please fix this bug by adding a pointer to determine whether buf is null or not in the two functions I mentioned, otherwise any time you call the editor control will crash in the click event, if the editor does not load the text. For example, after running gide, clicking on any area of the editor area without setting any text will cause a panic

**Comment by kkoreilly** [comment]
Thanks for reporting this and writing a fix. I applied your changes here and in gix (see https://github.com/goki/gide/commit/b2e93ab6214b9ee13f22825f489611fbfe1b1fe7 and https://github.com/goki/gix/commit/7dcce297ec47b06417ab0c61457c4aa11ae84345) and it no longer panics. Let me know if you have any other crashes.
